site_name: University Polling

# plugins:
  # - mike:
  #     # These fields are all optional; the defaults are as below...
  #     alias_type: symlink
  #     redirect_template: null
  #     deploy_prefix: ''
  #     canonical_version: null
  #     version_selector: true
  #     css_dir: css
  #     javascript_dir: js

theme: 
  name: material
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.path
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotate
    - content.code.copy
    # - navigation.indexes 
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: deep purple
  icon:
    repo: fontawesome/brands/github

extra:
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unipoll
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Copyright in the footer
copyright: Copyright &copy; 2023 University Polling

# GitHub repository link in the header
repo_url: https://github.com/unipoll
repo_name: ""

# Markdown extensions
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
