name: update_gh_pages

on:
  workflow_dispatch:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    # k8s hosted Arc Runner not installed git for checking out submodules, see issue #2  
    runs-on: arc-runner-k8s
    # runs-on: self-hosted
    steps:
      - name: Force update git
        run:
          run: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:git-core/ppa
            sudo apt-get update
            sudo apt-get install -y git
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
